spring:
  application:
    name: gateway-service-zuul

server:
  port: 8888
  context-path: /api
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka
ribbon:
  eureka:
    enabled: false
zuul:
  routes:
    gateway-service-zuul:
      path: /api/**
      url: forward:/
    producer:
      path: /producer/**
      url: localhost:9000
    consumer:
      path: /consumer
      url: localhost:9001

